/**
 * DATABASE SCHEMA MAPPING
 * This file maps actual Supabase table/column names to app-friendly names
 * Based on introspected schema from Supabase database
 */

export const DB = {
  users: {
    table: "users",
    id: "id",
    authId: "auth_id",
    username: "username",
    email: "email",
    firstName: "first_name",
    lastName: "last_name",
    avatarId: "avatar_id",
    bio: "bio",
    location: "location",
    website: "website",
    links: "links",
    pronouns: "pronouns",
    gender: "gender",
    verified: "verified",
    followersCount: "followers_count",
    followingCount: "following_count",
    postsCount: "posts_count",
    createdAt: "created_at",
    updatedAt: "updated_at",
    isPrivate: "is_private",
  },
  posts: {
    table: "posts",
    id: "id",
    authorId: "author_id",
    content: "content",
    postKind: "post_kind",
    textTheme: "text_theme",
    location: "location",
    likesCount: "likes_count",
    commentsCount: "comments_count",
    bookmarksCount: "bookmarks_count",
    visibility: "visibility",
    isNsfw: "is_nsfw",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
  postsMedia: {
    table: "posts_media",
    id: "id",
    parentId: "_parent_id",
    type: "type",
    url: "url",
    imageId: "image_id",
    order: "_order",
    mimeType: "mime_type",
    livePhotoVideoUrl: "live_photo_video_url",
  },
  postTextSlides: {
    table: "post_text_slides",
    id: "id",
    postId: "post_id",
    slideIndex: "slide_index",
    content: "content",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
  stories: {
    table: "stories",
    id: "id",
    authorId: "author_id",
    mediaId: "media_id",
    thumbnailId: "thumbnail_id",
    caption: "caption",
    location: "location",
    visibility: "visibility",
    expiresAt: "expires_at",
    viewCount: "view_count",
    viewersCount: "viewers_count",
    createdAt: "created_at",
    livePhotoVideoUrl: "live_photo_video_url",
  },
  likes: {
    table: "likes",
    id: "id",
    userId: "user_id",
    postId: "post_id",
    createdAt: "created_at",
  },
  comments: {
    table: "comments",
    id: "id",
    postId: "post_id",
    authorId: "author_id",
    parentId: "parent_id",
    rootId: "root_id",
    depth: "depth",
    content: "content",
    likesCount: "likes_count",
    createdAt: "created_at",
  },
  follows: {
    table: "follows",
    id: "id",
    followerId: "follower_id",
    followingId: "following_id",
    createdAt: "created_at",
  },
  bookmarks: {
    table: "bookmarks",
    id: "id",
    userId: "user_id",
    postId: "post_id",
    createdAt: "created_at",
  },
  notifications: {
    table: "notifications",
    id: "id",
    recipientId: "recipient_id",
    actorId: "actor_id",
    type: "type",
    read: "read",
    createdAt: "created_at",
  },
  events: {
    table: "events",
    id: "id",
    hostId: "host_id",
    title: "title",
    description: "description",
    startDate: "start_date",
    endDate: "end_date",
    location: "location",
    coverImageUrl: "cover_image_url",
    price: "price",
    maxAttendees: "max_attendees",
    totalAttendees: "total_attendees",
    isOnline: "is_online",
    images: "images",
    youtubeVideoUrl: "youtube_video_url",
    flyerImageUrl: "flyer_image_url",
    flyerImageMeta: "flyer_image_meta",
    createdAt: "created_at",
  },
  spotlightCampaigns: {
    table: "event_spotlight_campaigns",
    id: "id",
    eventId: "event_id",
    cityId: "city_id",
    organizerId: "organizer_id",
    placement: "placement",
    priority: "priority",
    status: "status",
    startsAt: "starts_at",
    endsAt: "ends_at",
    stripePaymentIntentId: "stripe_payment_intent_id",
    amountCents: "amount_cents",
    currency: "currency",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
  storyTags: {
    table: "story_tags",
    id: "id",
    storyId: "story_id",
    taggedUserId: "tagged_user_id",
    xPosition: "x_position",
    yPosition: "y_position",
    createdAt: "created_at",
  },
  postTags: {
    table: "post_tags",
    id: "id",
    postId: "post_id",
    taggedUserId: "tagged_user_id",
    taggedByUserId: "tagged_by_user_id",
    xPosition: "x_position",
    yPosition: "y_position",
    mediaIndex: "media_index",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
  eventLikes: {
    table: "event_likes",
    id: "id",
    eventId: "event_id",
    userId: "user_id",
    createdAt: "created_at",
  },
  eventRsvps: {
    table: "event_rsvps",
    id: "id",
    eventId: "event_id",
    userId: "user_id",
    status: "status",
    createdAt: "created_at",
  },
  conversations: {
    table: "conversations",
    id: "id",
    isGroup: "is_group",
    groupName: "group_name",
    lastMessageAt: "last_message_at",
    createdAt: "created_at",
  },
  conversationsRels: {
    table: "conversations_rels",
    parentId: "parent_id",
    usersId: "users_id",
  },
  conversationReads: {
    table: "conversation_reads",
    conversationId: "conversation_id",
    userId: "user_id",
    lastReadAt: "last_read_at",
    updatedAt: "updated_at",
  },
  messages: {
    table: "messages",
    id: "id",
    conversationId: "conversation_id",
    senderId: "sender_id",
    content: "content",
    metadata: "metadata",
    readAt: "read_at",
    createdAt: "created_at",
  },
  storyViews: {
    table: "story_views",
    storyId: "story_id",
    userId: "user_id",
    viewedAt: "viewed_at",
  },
  media: {
    table: "media",
    id: "id",
    url: "url",
    filename: "filename",
    mimeType: "mime_type",
    filesize: "filesize",
    width: "width",
    height: "height",
    ownerId: "owner_id",
    createdAt: "created_at",
  },
  // ── Events V2 columns (additive) ───────────────────────────
  eventsV2: {
    visibility: "visibility",
    category: "category",
    locationType: "location_type",
    locationName: "location_name",
    locationAddress: "location_address",
    locationLat: "location_lat",
    locationLng: "location_lng",
    vibesMedia: "vibes_media",
    disclaimers: "disclaimers",
    nsfw: "nsfw",
    ageRestriction: "age_restriction",
    ticketingEnabled: "ticketing_enabled",
    payoutStatus: "payout_status",
    payoutReleaseAt: "payout_release_at",
    shareSlug: "share_slug",
    updatedAt: "updated_at",
  },
  // ── Ticket types ───────────────────────────────────────────
  ticketTypes: {
    table: "ticket_types",
    id: "id",
    eventId: "event_id",
    name: "name",
    priceCents: "price_cents",
    currency: "currency",
    quantityTotal: "quantity_total",
    quantitySold: "quantity_sold",
    maxPerUser: "max_per_user",
    saleStart: "sale_start",
    saleEnd: "sale_end",
    createdAt: "created_at",
  },
  // ── Tickets ────────────────────────────────────────────────
  tickets: {
    table: "tickets",
    id: "id",
    eventId: "event_id",
    ticketTypeId: "ticket_type_id",
    userId: "user_id",
    status: "status",
    qrToken: "qr_token",
    checkedInAt: "checked_in_at",
    checkedInBy: "checked_in_by",
    stripeCheckoutSessionId: "stripe_checkout_session_id",
    stripePaymentIntentId: "stripe_payment_intent_id",
    purchaseAmountCents: "purchase_amount_cents",
    createdAt: "created_at",
  },
  // ── Event invites ──────────────────────────────────────────
  eventInvites: {
    table: "event_invites",
    id: "id",
    eventId: "event_id",
    invitedUserId: "invited_user_id",
    invitedEmail: "invited_email",
    status: "status",
    createdAt: "created_at",
  },
  // ── Event financials ───────────────────────────────────────
  eventFinancials: {
    table: "event_financials",
    eventId: "event_id",
    grossCents: "gross_cents",
    refundsCents: "refunds_cents",
    dvntFeeCents: "dvnt_fee_cents",
    stripeFeeCents: "stripe_fee_cents",
    netCents: "net_cents",
    calculatedAt: "calculated_at",
  },
  // ── Organizer accounts ─────────────────────────────────────
  organizerAccounts: {
    table: "organizer_accounts",
    hostId: "host_id",
    stripeAccountId: "stripe_account_id",
    chargesEnabled: "charges_enabled",
    payoutsEnabled: "payouts_enabled",
    detailsSubmitted: "details_submitted",
    createdAt: "created_at",
    updatedAt: "updated_at",
  },
  // ── Payouts ────────────────────────────────────────────────
  payouts: {
    table: "payouts",
    id: "id",
    eventId: "event_id",
    hostId: "host_id",
    stripePayoutId: "stripe_payout_id",
    status: "status",
    grossCents: "gross_cents",
    netCents: "net_cents",
    releaseAt: "release_at",
    createdAt: "created_at",
  },
  // ── Reports ────────────────────────────────────────────────
  reportsEvents: {
    table: "reports_events",
    id: "id",
    eventId: "event_id",
    reporterId: "reporter_id",
    reason: "reason",
    details: "details",
    createdAt: "created_at",
  },
  // ── Stripe idempotency ─────────────────────────────────────
  stripeEvents: {
    table: "stripe_events",
    eventId: "event_id",
    eventType: "event_type",
    processedAt: "processed_at",
  },
  // ── Sneaky access (paywall) ────────────────────────────────
  sneakyAccess: {
    table: "sneaky_access",
    sessionId: "session_id",
    userId: "user_id",
    amountCents: "amount_cents",
    currency: "currency",
    stripeCheckoutSessionId: "stripe_checkout_session_id",
    stripePaymentIntentId: "stripe_payment_intent_id",
    createdAt: "created_at",
  },
  // ── Cities (Near Me) ─────────────────────────────────────────
  cities: {
    table: "cities",
    id: "id",
    name: "name",
    state: "state",
    country: "country",
    lat: "lat",
    lng: "lng",
    timezone: "timezone",
    population: "population",
    slug: "slug",
    createdAt: "created_at",
  },
  // ── User location columns ───────────────────────────────────
  userLocation: {
    cityId: "city_id",
    locationMode: "location_mode",
    deviceLat: "device_lat",
    deviceLng: "device_lng",
    locationUpdatedAt: "location_updated_at",
  },
  // ── Ads config (Decellus scaffold) ─────────────────────────
  adsConfig: {
    table: "ads_config",
    id: "id",
    placementKey: "placement_key",
    title: "title",
    imageUrl: "image_url",
    tapUrl: "tap_url",
    active: "active",
    createdAt: "created_at",
  },
} as const;
