/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalNodes_E13979C0".
 */
export type LexicalNodes_E13979C0 =
  | SerializedTextNode
  | SerializedTabNode
  | SerializedLineBreakNode
  | SerializedParagraphNode<LexicalNodes_E13979C0>
  | SerializedBlockNode<
      | PullQuote
      | ImageGallery
      | VideoEmbed
      | StatBlock
      | EventCallout
      | AppCta
      | NewsletterCta
      | RelatedPostsBlock
      | Timeline
      | Faq
      | Divider
      | SideNote
      | SponsoredDisclosure
    >
  | SerializedHorizontalRuleNode
  | SerializedUploadNode<'media', LexicalUploadFields_7C90EEAC>
  | SerializedAutoLinkNode<LexicalNodes_E13979C0, LexicalLinkFields>
  | SerializedLinkNode<LexicalNodes_E13979C0, LexicalLinkFields>
  | SerializedHeadingNode<LexicalNodes_E13979C0, 'h1' | 'h2' | 'h3' | 'h4'>
  | SerializedQuoteNode<LexicalNodes_E13979C0>
  | SerializedRelationshipNode<
      | 'admin-users'
      | 'members'
      | 'reports'
      | 'events'
      | 'tickets'
      | 'ban-list'
      | 'moderation-actions'
      | 'posts'
      | 'categories'
      | 'authors'
      | 'comments'
      | 'payload-kv'
      | 'payload-locked-documents'
      | 'payload-preferences'
      | 'payload-migrations'
    >
  | SerializedListNode<LexicalNodes_E13979C0>
  | SerializedListItemNode<LexicalNodes_E13979C0>;

export interface Config {
  auth: {
    'admin-users': AdminUserAuthOperations;
  };
  blocks: {};
  collections: {
    'admin-users': AdminUser;
    members: Member;
    reports: Report;
    events: Event;
    tickets: Ticket;
    'ban-list': BanList;
    'moderation-actions': ModerationAction;
    posts: Post;
    categories: Category;
    authors: Author;
    media: Media;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'admin-users': AdminUsersSelect<false> | AdminUsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    'ban-list': BanListSelect<false> | BanListSelect<true>;
    'moderation-actions': ModerationActionsSelect<false> | ModerationActionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: AdminUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users".
 */
export interface AdminUser {
  id: number;
  name?: string | null;
  /**
   * App avatar (copied at promotion)
   */
  avatarUrl?: string | null;
  role: 'super_admin' | 'admin' | 'moderator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  username: string;
  email?: string | null;
  avatarUrl?: string | null;
  /**
   * Supabase/Better Auth user id
   */
  appUserId?: string | null;
  status: 'active' | 'under_review' | 'warned' | 'suspended' | 'shadow_banned' | 'banned';
  lastModerationReason?: string | null;
  suspendedUntil?: string | null;
  openReportsAgainst?: number | null;
  timesBlocked?: number | null;
  lastIp?: string | null;
  appleSub?: string | null;
  deviceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  reportedMember: number | Member;
  reporter?: (number | null) | Member;
  reason: string;
  details?: string | null;
  category?: ('harassment' | 'spam' | 'safety' | 'impersonation' | 'hate' | 'violence' | 'comment' | 'other') | null;
  /**
   * Set when the report targets a specific comment.
   */
  reportedComment?: (number | null) | Comment;
  status: 'open' | 'resolved' | 'dismissed';
  resolutionNote?: string | null;
  resolvedBy?: (number | null) | AdminUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  authorMember: number | Member;
  parent?: (number | null) | Comment;
  /**
   * Top-level ancestor; equals self for roots.
   */
  threadRoot?: (number | null) | Comment;
  depth?: number | null;
  body: string;
  status: 'visible' | 'removed';
  shadowed?: boolean | null;
  editedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Dek / article summary shown in cards and hero.
   */
  excerpt?: string | null;
  /**
   * Short label above the title (e.g. "Culture", "Breaking")
   */
  eyebrow?: string | null;
  /**
   * Cinematic hero — 16:9 or wider preferred.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional hero video (muted autoplay loop).
   */
  heroVideoUrl?: string | null;
  heroCaption?: string | null;
  content: LexicalRichText<LexicalNodes_E13979C0>;
  contentHtml?: string | null;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary byline ("By …")
   */
  authors?: (number | Author)[] | null;
  /**
   * Secondary credits shown beneath the byline ("Photographs by …")
   */
  contributors?:
    | {
        author: number | Author;
        /**
         * e.g. "Photographs by", "Video by", "Reporting by", "Edited by"
         */
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pin to hero / featured slot on index.
   */
  featured?: boolean | null;
  /**
   * Show in Editor's Picks rail.
   */
  editorsPick?: boolean | null;
  /**
   * Show in Trending rail.
   */
  trending?: boolean | null;
  /**
   * Estimated read time in minutes. Auto-calculated from content on save.
   */
  readTime?: number | null;
  relatedPosts?: (number | Post)[] | null;
  publishedAt?: string | null;
  updatedAt: string;
  seo?: {
    /**
     * Defaults to post title.
     */
    title?: string | null;
    /**
     * Defaults to excerpt.
     */
    description?: string | null;
    /**
     * OG image (1200×630). Defaults to heroImage.
     */
    ogImage?: (number | null) | Media;
    /**
     * Canonical URL override.
     */
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
    /**
     * Raw JSON-LD override (merged with auto-generated Article schema).
     */
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  coverImage?: (number | null) | Media;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  creditText?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  description?: string | null;
  /**
   * Hex or CSS color token for the category accent (e.g. #FF5BFC, #3FDCFF).
   */
  accentColor?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Lower = displayed first in the category rail.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug?: string | null;
  email?: string | null;
  /**
   * e.g. Editor-at-Large, Photographer, Staff Writer
   */
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  socials?: {
    instagram?: string | null;
    twitter?: string | null;
    tiktok?: string | null;
    website?: string | null;
  };
  /**
   * Link to author profile page if external
   */
  profileUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Live app event id
   */
  appEventId?: string | null;
  status?: ('draft' | 'published' | 'cancelled' | 'ended') | null;
  startsAt?: string | null;
  endsAt?: string | null;
  capacity?: number | null;
  location?: string | null;
  /**
   * Organizer of record. Reassign with care — audited.
   */
  host?: (number | null) | Member;
  /**
   * Edit tier name, price (cents), and inventory.
   */
  ticketTiers?:
    | {
        name: string;
        priceCents: number;
        quantity: number;
        soldCount?: number | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  attendees?: number | null;
  ticketsSold?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  /**
   * Event this ticket admits to.
   */
  event?: (number | null) | Event;
  /**
   * App user who holds the ticket (empty for guest tickets).
   */
  holder?: (number | null) | Member;
  /**
   * Ticket type / tier name.
   */
  tier?: string | null;
  /**
   * Name printed on the ticket. Editable.
   */
  attendeeName?: string | null;
  /**
   * Tickets in this holding. Editable.
   */
  quantity?: number | null;
  status?: ('valid' | 'checked_in' | 'cancelled' | 'refunded' | 'transferred' | 'pending') | null;
  guestEmail?: string | null;
  purchasedAt?: string | null;
  /**
   * Scan token (read-only).
   */
  qrToken?: string | null;
  appTicketId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hashed ban-evasion keys. Managed by moderation hooks; lift a ban by reinstating the member.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ban-list".
 */
export interface BanList {
  id: number;
  keyType: 'email' | 'name' | 'ip' | 'apple_sub' | 'device';
  keyHash: string;
  member?: (number | null) | Member;
  active?: boolean | null;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-actions".
 */
export interface ModerationAction {
  id: number;
  member: number | Member;
  action: string;
  previousStatus?: string | null;
  reason?: string | null;
  actor?: (number | null) | AdminUser;
  suspendedUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admin-users';
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'ban-list';
        value: number | BanList;
      } | null)
    | ({
        relationTo: 'moderation-actions';
        value: number | ModerationAction;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admin-users';
    value: number | AdminUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admin-users';
    value: number | AdminUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  avatarUrl?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  username?: T;
  email?: T;
  avatarUrl?: T;
  appUserId?: T;
  status?: T;
  lastModerationReason?: T;
  suspendedUntil?: T;
  openReportsAgainst?: T;
  timesBlocked?: T;
  lastIp?: T;
  appleSub?: T;
  deviceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reportedMember?: T;
  reporter?: T;
  reason?: T;
  details?: T;
  category?: T;
  reportedComment?: T;
  status?: T;
  resolutionNote?: T;
  resolvedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  appEventId?: T;
  status?: T;
  startsAt?: T;
  endsAt?: T;
  capacity?: T;
  location?: T;
  host?: T;
  ticketTiers?:
    | T
    | {
        name?: T;
        priceCents?: T;
        quantity?: T;
        soldCount?: T;
        active?: T;
        id?: T;
      };
  attendees?: T;
  ticketsSold?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  event?: T;
  holder?: T;
  tier?: T;
  attendeeName?: T;
  quantity?: T;
  status?: T;
  guestEmail?: T;
  purchasedAt?: T;
  qrToken?: T;
  appTicketId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ban-list_select".
 */
export interface BanListSelect<T extends boolean = true> {
  keyType?: T;
  keyHash?: T;
  member?: T;
  active?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-actions_select".
 */
export interface ModerationActionsSelect<T extends boolean = true> {
  member?: T;
  action?: T;
  previousStatus?: T;
  reason?: T;
  actor?: T;
  suspendedUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  eyebrow?: T;
  heroImage?: T;
  heroVideoUrl?: T;
  heroCaption?: T;
  content?: T;
  contentHtml?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  authors?: T;
  contributors?:
    | T
    | {
        author?: T;
        role?: T;
        id?: T;
      };
  featured?: T;
  editorsPick?: T;
  trending?: T;
  readTime?: T;
  relatedPosts?: T;
  publishedAt?: T;
  updatedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        structuredData?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  coverImage?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  accentColor?: T;
  featuredImage?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  email?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  socials?:
    | T
    | {
        instagram?: T;
        twitter?: T;
        tiktok?: T;
        website?: T;
      };
  profileUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  creditText?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  authorMember?: T;
  parent?: T;
  threadRoot?: T;
  depth?: T;
  body?: T;
  status?: T;
  shadowed?: T;
  editedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuote".
 */
export interface PullQuote {
  id: string;
  blockType: 'pullQuote';
  quote: string;
  attribution?: string | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGallery".
 */
export interface ImageGallery {
  id: string;
  blockType: 'imageGallery';
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid' | 'masonry' | 'carousel' | 'fullWidth') | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbed".
 */
export interface VideoEmbed {
  id: string;
  blockType: 'videoEmbed';
  /**
   * YouTube, Vimeo, or direct video URL
   */
  url: string;
  caption?: string | null;
  autoplay?: boolean | null;
  poster?: (number | null) | Media;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatBlock".
 */
export interface StatBlock {
  id: string;
  blockType: 'statBlock';
  stats?:
    | {
        value: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventCallout".
 */
export interface EventCallout {
  id: string;
  blockType: 'eventCallout';
  event?: (number | null) | Event;
  headline?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AppCta".
 */
export interface AppCta {
  id: string;
  blockType: 'appCta';
  headline?: string | null;
  body?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  image?: (number | null) | Media;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterCta".
 */
export interface NewsletterCta {
  id: string;
  blockType: 'newsletterCta';
  headline?: string | null;
  body?: string | null;
  placeholder?: string | null;
  buttonLabel?: string | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RelatedPostsBlock".
 */
export interface RelatedPostsBlock {
  id: string;
  blockType: 'relatedPostsBlock';
  headline?: string | null;
  posts?: (number | Post)[] | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Timeline".
 */
export interface Timeline {
  id: string;
  blockType: 'timeline';
  items?:
    | {
        date: string;
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Faq".
 */
export interface Faq {
  id: string;
  blockType: 'faq';
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Divider".
 */
export interface Divider {
  id: string;
  blockType: 'divider';
  style?: ('line' | 'ornament' | 'stars' | 'space') | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SideNote".
 */
export interface SideNote {
  id: string;
  blockType: 'sideNote';
  body: string;
  type?: ('info' | 'warning' | 'quote' | 'tip') | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsoredDisclosure".
 */
export interface SponsoredDisclosure {
  id: string;
  blockType: 'sponsoredDisclosure';
  text?: string | null;
  blockName?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LexicalUploadFields_7C90EEAC".
 */
export interface LexicalUploadFields_7C90EEAC {
  caption?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

/** @internal Core Lexical types — see @payloadcms/richtext-lexical. */
export type LexicalElementFormat = 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
export type LexicalElementDirection = ('ltr' | 'rtl') | null;

export interface SerializedLexicalElementBase<TChildren> {
  children: TChildren[];
  direction: LexicalElementDirection;
  format: LexicalElementFormat;
  indent: number;
  textFormat?: number;
  textStyle?: string;
  version: number;
}

export type LexicalTextMode = 'normal' | 'token' | 'segmented';

export interface SerializedTextNode {
  type: 'text';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedTabNode {
  type: 'tab';
  detail: number;
  format: number;
  mode: LexicalTextMode;
  style: string;
  text: string;
  version: number;
}

export interface SerializedLineBreakNode {
  type: 'linebreak';
  version: number;
}

export interface SerializedParagraphNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'paragraph';
  textFormat: number;
  textStyle: string;
}

export type SerializedBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'block';
  format: LexicalElementFormat;
  version: number;
  fields: { id: string; blockName?: string | null } & Omit<TFields, 'id' | 'blockName'>;
} : never;
export type SerializedInlineBlockNode<TFields extends { blockType: string }> = TFields extends unknown ? {
  type: 'inlineBlock';
  version: number;
  fields: { id: string } & Omit<TFields, 'id'>;
} : never;

export interface SerializedHorizontalRuleNode {
  type: 'horizontalrule';
  version: number;
}

export type SerializedUploadNode<TSlugs extends keyof Config['collections'], TFields = { [k: string]: unknown }> = {
  type: 'upload';
  format: LexicalElementFormat;
  id: string;
  version: number;
  fields: TFields;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: number | string | Config['collections'][TSlug];
  };
}[TSlugs];

export interface LexicalLinkFields {
  [k: string]: unknown;
  doc?: {
    relationTo: string;
    value: Config['db']['defaultIDType'] | { [k: string]: unknown; id: Config['db']['defaultIDType'] };
  } | null;
  linkType: 'custom' | 'internal';
  newTab: boolean;
  url?: string;
}
export interface SerializedLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'link';
  fields: TFields;
  id?: string;
}
export interface SerializedAutoLinkNode<TChildren, TFields = LexicalLinkFields> extends SerializedLexicalElementBase<TChildren> {
  type: 'autolink';
  fields: TFields;
}

export interface SerializedHeadingNode<
  TChildren,
  TTag extends 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6',
> extends SerializedLexicalElementBase<TChildren> {
  type: 'heading';
  tag: TTag;
}

export interface SerializedQuoteNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'quote';
}

export type SerializedRelationshipNode<TSlugs extends keyof Config['collections']> = {
  type: 'relationship';
  format: LexicalElementFormat;
  version: number;
} & {
  [TSlug in TSlugs]: {
    relationTo: TSlug;
    value: number | string | Config['collections'][TSlug];
  };
}[TSlugs];

export interface SerializedListNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'list';
  checked?: boolean;
  listType: 'number' | 'bullet' | 'check';
  start: number;
  tag: 'ul' | 'ol';
}

export interface SerializedListItemNode<TChildren> extends SerializedLexicalElementBase<TChildren> {
  type: 'listitem';
  checked?: boolean;
  value: number;
}

/** Shape of a Lexical `richText` field. */
export interface LexicalRichText<TNode> {
  root: {
    children: TNode[];
    direction: LexicalElementDirection;
    format: LexicalElementFormat;
    indent: number;
    type: 'root';
    version: number;
  };
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}