import SwiftUI

/// The real DVNT wordmark — rendered from the `dvntLogo` imageset generated by
/// apple-targets from `DVNT-logo-grad-white.png` (a 2360x908 raster of the brand
/// wordmark SVG; white glyphs on transparent, gradient intact). Never redrawn.
struct DVNTLogoView: View {
    /// Fixed height; width follows the wordmark's 2360x908 aspect.
    var height: CGFloat = 22

    /// Take the width offered and let height follow the aspect instead.
    ///
    /// A fixed height cannot serve both sizes: the same 30pt mark is 38% of a
    /// 205pt Ultra screen and 48% of a 162pt SE. The Door wants the mark to
    /// read at the same *proportion* on every watch, which is a width problem,
    /// not a height one.
    var fillWidth: Bool = false

    var body: some View {
        let mark = Image("dvntLogo").resizable().scaledToFit()
        Group {
            if fillWidth {
                mark.frame(maxWidth: .infinity)
            } else {
                mark.frame(height: height)
            }
        }
        .accessibilityLabel("DVNT")
    }
}
