import SwiftUI

/// The real DVNT wordmark — rendered from the `dvntLogo` imageset generated by
/// apple-targets from `DVNT-logo-grad-white.png` (a 2360x908 raster of the brand
/// wordmark SVG; white glyphs on transparent, gradient intact). Never redrawn.
struct DVNTLogoView: View {
    var height: CGFloat = 22

    var body: some View {
        Image("dvntLogo")
            .resizable()
            .scaledToFit()
            .frame(height: height)
            .accessibilityLabel("DVNT")
    }
}

/// Launch / loading state: gradient wordmark on true-black.
struct LaunchView: View {
    var body: some View {
        ZStack {
            DVNT.canvas.ignoresSafeArea()
            VStack(spacing: 10) {
                DVNTLogoView(height: 26)
                ProgressView()
                    .tint(DVNT.accent)
            }
        }
    }
}
