/**
 * expo-widgets adapter for the DVNT Live Surface (iOS Live Activities).
 *
 * Replaces the disabled hand-rolled `DVNTLiveActivity` ActivityKit native module
 * (which crashed at launch) with `expo-widgets`, WITHOUT changing this file's
 * public API. `use-live-surface` still imports the same three functions:
 *   - areLiveActivitiesEnabled()
 *   - updateLiveActivity(payload)
 *   - endLiveActivity()
 * and a new push-to-start listener is exported for the app-lifecycle wiring.
 *
 * expo-widgets is an iOS-only native module in this app. It is required lazily
 * behind a Platform guard so the Android and web bundles never resolve it, and
 * the layout component (which pulls in `@expo/ui/swift-ui`) lives in a separate
 * file that is only `require`d on iOS.
 *
 * APIs used (verified against node_modules/expo-widgets/build/Widgets.d.ts):
 *   createLiveActivity(name, layout) -> LiveActivityFactory
 *     .start(props, url?) -> LiveActivity
 *     .getInstances() -> LiveActivity[]
 *   LiveActivity.update(props): Promise<void>
 *   LiveActivity.end(dismissalPolicy?, props?, contentDate?): Promise<void>
 *   addPushToStartTokenListener(listener) -> EventSubscription
 */
import { Platform } from "react-native";

import type { LiveSurfacePayload } from "../types";

// Type-only imports are erased at compile time, so they never reach the web/Android bundle.
import type {
  LiveActivity,
  LiveActivityFactory,
  LiveActivityComponent,
} from "expo-widgets";

const isIOS = Platform.OS === "ios";

// Must match the `name` used when the Live Activity target is generated by the
// expo-widgets config plugin.
const ACTIVITY_NAME = "DVNTLiveSurface";

type WidgetsModule = typeof import("expo-widgets");

let widgets: WidgetsModule | null = null;
if (isIOS) {
  try {
    widgets = require("expo-widgets") as WidgetsModule;
  } catch {
    widgets = null;
  }
}

// The factory instantiates a native SharedObject, so it is built lazily and
// only on iOS. The layout is required here (not imported) so `@expo/ui/swift-ui`
// stays out of non-iOS bundles.
let factory: LiveActivityFactory<LiveSurfacePayload> | null = null;

function getFactory(): LiveActivityFactory<LiveSurfacePayload> | null {
  if (!isIOS || !widgets) return null;
  if (!factory) {
    try {
      const { liveSurfaceLayout } =
        require("./live-activity-layout") as {
          liveSurfaceLayout: LiveActivityComponent<LiveSurfacePayload>;
        };
      factory = widgets.createLiveActivity<LiveSurfacePayload>(
        ACTIVITY_NAME,
        liveSurfaceLayout,
      );
    } catch (e) {
      console.warn("[LiveSurface] createLiveActivity failed:", e);
      factory = null;
    }
  }
  return factory;
}

/**
 * Whether Live Activities can be driven on this device/build.
 *
 * expo-widgets does not surface ActivityKit's `ActivityAuthorizationInfo`
 * (the user "Live Activities" toggle), so — matching the old bridge's
 * platform/module-presence check — this returns true on iOS when the
 * expo-widgets native module is available, false otherwise. No invented
 * native method is called.
 */
export async function areLiveActivitiesEnabled(): Promise<boolean> {
  return isIOS && !!widgets;
}

/**
 * Start the DVNT Live Activity, or update it if one is already running.
 * The payload is passed straight through as the activity content state; the
 * layout component derives its view from it.
 */
export function updateLiveActivity(payload: LiveSurfacePayload): void {
  const f = getFactory();
  if (!f) return;
  try {
    const instances = f.getInstances();
    if (instances.length > 0) {
      for (const activity of instances) {
        activity.update(payload).catch((e) => {
          console.warn("[LiveSurface] update failed:", e);
        });
      }
    } else {
      f.start(payload, payload.tile1?.deepLink);
    }
  } catch (e) {
    console.warn("[LiveSurface] updateLiveActivity failed:", e);
  }
}

/**
 * End all active DVNT Live Activities immediately.
 */
export function endLiveActivity(): void {
  const f = getFactory();
  if (!f) return;
  try {
    for (const activity of f.getInstances() as LiveActivity<LiveSurfacePayload>[]) {
      activity.end("immediate").catch((e) => {
        console.warn("[LiveSurface] end failed:", e);
      });
    }
  } catch (e) {
    console.warn("[LiveSurface] endLiveActivity failed:", e);
  }
}

/**
 * Subscribe to push-to-start tokens. This token is registered with APNs so the
 * server can START a Live Activity remotely (`push-type.liveactivity`) while the
 * app is backgrounded — the foreground-only `updateLiveActivity` cannot.
 *
 * Returns an unsubscribe function. No-op on Android/web or when the module is
 * unavailable.
 */
export function addLiveActivityPushToStartListener(
  onToken: (token: string) => void,
): () => void {
  if (!isIOS || !widgets) return () => {};
  try {
    const sub = widgets.addPushToStartTokenListener((event) => {
      if (event?.activityPushToStartToken) {
        onToken(event.activityPushToStartToken);
      }
    });
    return () => sub.remove();
  } catch (e) {
    console.warn("[LiveSurface] addPushToStartTokenListener failed:", e);
    return () => {};
  }
}
