import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ApiProvider } from "@dvnt/api";
import { ImageProvider } from "@dvnt/ui/image-provider";
import { SiteChrome } from "@/components/site-chrome";
import { WebVitalsReporter } from "@/components/web-vitals-reporter";
import { WebToaster } from "@/components/web-toaster";
import { RNWStyleRegistry } from "./registry";
import { RegisterSW } from "@/components/pwa/register-sw";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Next 16 moved themeColor out of metadata.
export const viewport: Viewport = {
  themeColor: "#0a0408",
};

export const metadata: Metadata = {
  metadataBase: new URL(getSolitoNextUrl()),
  title: "dvnt.app | connect. gather. move.",
  description: "DVNT app exists to create an intentional space for queer people to connect, gather, and move culture on their own terms.",
  // PWA / iOS install signal. The manifest is generated by app/manifest.ts.
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    title: "DVNT",
    statusBarStyle: "black-translucent",
  },
  icons: {
    // Browser tab / favicon uses the DVNT app logo.
    icon: "/favicon.ico",
    // iOS uses apple-touch-icon for the Home Screen icon — distinct from
    // the manifest icons (which Android consumes). Same artwork as the
    // native iOS app icon.
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    title: "dvnt.app | connect. gather. move.",
    description: "DVNT app exists to create an intentional space for queer people to connect, gather, and move culture on their own terms.",
    siteName: "DVNT",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "dvnt.app | connect. gather. move.",
    description: "DVNT app exists to create an intentional space for queer people to connect, gather, and move culture on their own terms.",
  },
};

function getSolitoNextUrl(): `http:${string}` | `https:${string}` {
  const url = process.env.NEXT_PUBLIC_SITE_URL;
  return url?.startsWith("http://") || url?.startsWith("https://")
    ? (url as `http:${string}` | `https:${string}`)
    : "http://localhost:3000";
}

/**
 * Frontend root layout — owns the <html>/<body> for the public DVNT site
 * (Solito screens, blog, events). Lives in the (frontend) route group so the
 * Payload admin in (payload) can render its OWN <html>/<body> without the
 * site chrome or react-native-web registry wrapping it. The top-level
 * app/layout.tsx is a pass-through that delegates to these per-group roots.
 */
export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Deviant top progress bar. The gradient + glow are themed in
            globals.css (#nprogress overrides); color here is the fallback. */}
        <NextTopLoader
          color="#FF5BFC"
          height={3}
          shadow="0 0 12px #FF5BFC, 0 0 8px #3FDCFF"
          showSpinner={false}
          easing="cubic-bezier(0.22,1,0.36,1)"
          speed={400}
        />
        <RNWStyleRegistry>
          <ImageProvider nextJsURL={getSolitoNextUrl()}>
            <ApiProvider>
              <WebVitalsReporter />
              {/* PWA shell — registers /sw.js + hydrates the install funnel
                  state (platform, display-mode, captured beforeinstallprompt).
                  Renders nothing; mount-once side effect. */}
              <RegisterSW />
              {/* Persistent header + footer wrapping every page — mounted once
                  at the root, so the chrome never remounts/jumps on navigation. */}
              <SiteChrome>{children}</SiteChrome>
              {/* Single web toast host — the RNW auth screens call sonner's
                  `toast.*`; without this nothing rendered (silent login errors). */}
              <WebToaster />
            </ApiProvider>
          </ImageProvider>
        </RNWStyleRegistry>
      </body>
    </html>
  );
}
