export const events = [
  {
    id: "lower-east-side-winter-bar-fest",
    title: "Lower East Side Winter Bar Fest",
    date: "17",
    month: "JAN",
    time: "6:00 PM",
    location: "Lower East Side, NY",
    price: 35,
    image:
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&h=1000&fit=crop",
    attendees: [
      { image: "https://i.pravatar.cc/150?img=5", name: "Sarah" },
      { image: "https://i.pravatar.cc/150?img=9", name: "Maria" },
      { name: "JD", initials: "JD" },
      { image: "https://i.pravatar.cc/150?img=10", name: "Emma" },
      { image: "https://i.pravatar.cc/150?img=12", name: "John" },
    ],
    totalAttendees: 127,
    likes: 1100,
    category: "Nightlife",
  },
  {
    id: "brooklyn-jazz-night",
    title: "Brooklyn Jazz Night",
    date: "18",
    month: "JAN",
    time: "8:00 PM",
    location: "Brooklyn, NY",
    price: 45,
    image:
      "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&h=1000&fit=crop",
    attendees: [
      { image: "https://i.pravatar.cc/150?img=10", name: "Emma" },
      { name: "MK", initials: "MK" },
      { image: "https://i.pravatar.cc/150?img=12", name: "John" },
      { image: "https://i.pravatar.cc/150?img=16", name: "Alex" },
      { image: "https://i.pravatar.cc/150?img=20", name: "Lisa" },
    ],
    totalAttendees: 89,
    likes: 850,
    category: "Music",
  },
  {
    id: "rooftop-brunch-experience",
    title: "Rooftop Brunch Experience",
    date: "19",
    month: "JAN",
    time: "11:00 AM",
    location: "Manhattan, NY",
    price: 55,
    image:
      "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?w=800&h=1000&fit=crop",
    attendees: [
      { image: "https://i.pravatar.cc/150?img=16", name: "Alex" },
      { image: "https://i.pravatar.cc/150?img=20", name: "Lisa" },
      { name: "TC", initials: "TC" },
      { image: "https://i.pravatar.cc/150?img=5", name: "Sarah" },
      { name: "RS", initials: "RS" },
    ],
    totalAttendees: 156,
    likes: 2300,
    category: "Food & Drink",
  },
  {
    id: "tech-networking-mixer",
    title: "Tech Startup Networking Mixer",
    date: "23",
    month: "JAN",
    time: "6:30 PM",
    location: "SoHo, NY",
    price: 25,
    image:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=1000&fit=crop",
    attendees: [
      { name: "RS", initials: "RS" },
      { image: "https://i.pravatar.cc/150?img=5", name: "Sarah" },
      { name: "PK", initials: "PK" },
      { image: "https://i.pravatar.cc/150?img=9", name: "Maria" },
      { image: "https://i.pravatar.cc/150?img=12", name: "John" },
    ],
    totalAttendees: 203,
    likes: 1600,
    category: "Networking",
  },
  {
    id: "comedy-show-special",
    title: "Stand-Up Comedy Show Special",
    date: "24",
    month: "JAN",
    time: "7:00 PM",
    location: "Greenwich Village, NY",
    price: 30,
    image:
      "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&h=1000&fit=crop",
    attendees: [
      { image: "https://i.pravatar.cc/150?img=10", name: "Emma" },
      { image: "https://i.pravatar.cc/150?img=12", name: "John" },
      { name: "AZ", initials: "AZ" },
      { image: "https://i.pravatar.cc/150?img=16", name: "Alex" },
      { name: "GH", initials: "GH" },
    ],
    totalAttendees: 178,
    likes: 1450,
    category: "Entertainment",
  },
  {
    id: "art-gallery-opening",
    title: "Contemporary Art Gallery Opening",
    date: "25",
    month: "JAN",
    time: "5:00 PM",
    location: "Chelsea, NY",
    price: 20,
    image:
      "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&h=1000&fit=crop",
    attendees: [
      { image: "https://i.pravatar.cc/150?img=9", name: "Maria" },
      { name: "GH", initials: "GH" },
      { image: "https://i.pravatar.cc/150?img=16", name: "Alex" },
      { image: "https://i.pravatar.cc/150?img=20", name: "Lisa" },
      { name: "TC", initials: "TC" },
    ],
    totalAttendees: 94,
    likes: 720,
    category: "Art & Culture",
  },
];

export const AVATAR_COLORS = [
  "#FF6B6B",
  "#4ECDC4",
  "#45B7D1",
  "#FFA07A",
  "#98D8C8",
];
