-- Game Night launch deck v1. Original DVNT content — nightlife, door lines,
-- group chats, hangovers, and bad decisions. Stable versioned ids; moderation
-- additions flip `active` rather than rewriting history.

insert into public.game_night_cards (id, kind, text, pick, deck_version) values
-- ------------------------------ prompts (pick 1) ------------------------------
('v1-p-001','prompt','The bouncer said absolutely not tonight because of _____.',1,'v1'),
('v1-p-002','prompt','My group chat blew up at 3 AM over _____.',1,'v1'),
('v1-p-003','prompt','The DJ killed the whole vibe when they played _____.',1,'v1'),
('v1-p-004','prompt','Nobody talks about the real reason we got kicked out: _____.',1,'v1'),
('v1-p-005','prompt','My toxic party trait is _____.',1,'v1'),
('v1-p-006','prompt','The VIP section was just _____.',1,'v1'),
('v1-p-007','prompt','I knew the afters was going to be a problem when I saw _____.',1,'v1'),
('v1-p-008','prompt','The promoter definitely lied about _____.',1,'v1'),
('v1-p-009','prompt','Hangover math: two drinks plus _____ equals calling out of work.',1,'v1'),
('v1-p-010','prompt','The bathroom line was so long we missed _____.',1,'v1'),
('v1-p-011','prompt','Nothing says "I peaked too early" like _____.',1,'v1'),
('v1-p-012','prompt','The Uber driver definitely judged us for _____.',1,'v1'),
('v1-p-013','prompt','My friend swears they''re leaving early, then stays for _____.',1,'v1'),
('v1-p-014','prompt','The dress code said no _____, and somehow I still got in.',1,'v1'),
('v1-p-015','prompt','What''s actually in that birthday bottle service bottle?',1,'v1'),
('v1-p-016','prompt','The real reason the rooftop party got shut down: _____.',1,'v1'),
('v1-p-017','prompt','My drunk self keeps texting _____.',1,'v1'),
('v1-p-018','prompt','The club photographer captured my worst moment: _____.',1,'v1'),
('v1-p-019','prompt','Someone at the function brought _____ unironically.',1,'v1'),
('v1-p-020','prompt','If my situationship saw me right now, they''d see _____.',1,'v1'),
('v1-p-021','prompt','The lost-and-found box at the venue is just a pile of _____.',1,'v1'),
('v1-p-022','prompt','The pregame went sideways when someone suggested _____.',1,'v1'),
('v1-p-023','prompt','I can always tell the night went too far when _____ shows up in my camera roll.',1,'v1'),
('v1-p-024','prompt','The security guard and I bonded over _____.',1,'v1'),
('v1-p-025','prompt','My horoscope did NOT warn me about _____.',1,'v1'),
('v1-p-026','prompt','The DJ''s encore was just _____.',1,'v1'),
('v1-p-027','prompt','I''m not saying the party was bad, but the highlight was _____.',1,'v1'),
('v1-p-028','prompt','My ex walked in right when _____ happened.',1,'v1'),
('v1-p-029','prompt','The group''s "one drink then home" plan always ends with _____.',1,'v1'),
('v1-p-030','prompt','The venue''s secret back room is just for _____.',1,'v1'),
-- ------------------------------ prompts (pick 2) ------------------------------
('v1-p-031','prompt','I showed up wearing _____ and carrying _____. They still let me in.',2,'v1'),
('v1-p-032','prompt','_____ plus _____ is why we''re not allowed back at that bar.',2,'v1'),
('v1-p-033','prompt','The perfect night out starts with _____ and ends with _____.',2,'v1'),
('v1-p-034','prompt','My two drunk personalities are _____ and _____.',2,'v1'),
('v1-p-035','prompt','Nothing bonds a friendship like _____ and _____ at 4 AM.',2,'v1'),
('v1-p-036','prompt','The ticket said open bar, but really it was _____ and _____.',2,'v1'),
('v1-p-037','prompt','The hangover cure: _____ followed immediately by _____.',2,'v1'),
('v1-p-038','prompt','Our table ordered _____ and _____, and that''s when the tab became a group problem.',2,'v1'),
('v1-p-039','prompt','Rule one of the afters: never mix _____ with _____.',2,'v1'),
('v1-p-040','prompt','The group chat name changed to _____ after the _____ incident.',2,'v1'),
-- ------------------------------ answers ------------------------------
('v1-a-001','answer','the "I know the owner" guy',1,'v1'),
('v1-a-002','answer','a screenshot of a screenshot of a text',1,'v1'),
('v1-a-003','answer','wearing the promoter''s wristband upside down',1,'v1'),
('v1-a-004','answer','somebody''s cousin nobody actually knows',1,'v1'),
('v1-a-005','answer','crying in the bathroom but making it fashion',1,'v1'),
('v1-a-006','answer','an expired student ID',1,'v1'),
('v1-a-007','answer','the friend who peaked at the pregame',1,'v1'),
('v1-a-008','answer','a club flyer from a different city',1,'v1'),
('v1-a-009','answer','"one more song" energy',1,'v1'),
('v1-a-010','answer','three different Venmo requests for the same Uber',1,'v1'),
('v1-a-011','answer','the world''s saddest slice of pizza',1,'v1'),
('v1-a-012','answer','a person dressed as the venue''s health-code violation',1,'v1'),
('v1-a-013','answer','someone slow-dancing with a bar stool',1,'v1'),
('v1-a-014','answer','the confidence of a man in flip-flops at a rooftop party',1,'v1'),
('v1-a-015','answer','a QR code that just opens someone''s Mixcloud',1,'v1'),
('v1-a-016','answer','the birthday girl who does not want to be sung to',1,'v1'),
('v1-a-017','answer','explaining the door list to a door guy who does not care',1,'v1'),
('v1-a-018','answer','a lighter collection stolen from every smoker there',1,'v1'),
('v1-a-019','answer','the "where are you" text sent to the wrong group chat',1,'v1'),
('v1-a-020','answer','somebody FaceTiming their mom from the dance floor',1,'v1'),
('v1-a-021','answer','a girl group adopting a stray situationship',1,'v1'),
('v1-a-022','answer','the photobooth strip that ruins three relationships',1,'v1'),
('v1-a-023','answer','waking up with a wristband and zero memory',1,'v1'),
('v1-a-024','answer','a tab so large it becomes a shared trauma',1,'v1'),
('v1-a-025','answer','the guy filming a music video no one asked for',1,'v1'),
('v1-a-026','answer','a bottle of water sold at champagne prices',1,'v1'),
('v1-a-027','answer','someone''s situationship getting jumped in the comments',1,'v1'),
('v1-a-028','answer','a LinkedIn connection request from the DJ',1,'v1'),
('v1-a-029','answer','the friend who rates every exit on a scale of 1 to Uber surge',1,'v1'),
('v1-a-030','answer','pretending to vape a USB stick',1,'v1'),
('v1-a-031','answer','a stranger''s birthday sash adopted as a scarf',1,'v1'),
('v1-a-032','answer','the before-and-after photo nobody agreed to take',1,'v1'),
('v1-a-033','answer','asking the DJ for a song that cleared the floor',1,'v1'),
('v1-a-034','answer','a matching tattoo nobody remembers getting',1,'v1'),
('v1-a-035','answer','the "close friends only" story that hit main',1,'v1'),
('v1-a-036','answer','three grown men fighting over a mirror selfie',1,'v1'),
('v1-a-037','answer','a burrito eaten like it owes you money',1,'v1'),
('v1-a-038','answer','the ex who "just happened to be in the area"',1,'v1'),
('v1-a-039','answer','a karaoke performance that became a legal matter',1,'v1'),
('v1-a-040','answer','someone pronouncing the venue''s name wrong with total confidence',1,'v1'),
('v1-a-041','answer','the shared location that betrays the whole group',1,'v1'),
('v1-a-042','answer','a wedding veil at a techno party',1,'v1'),
('v1-a-043','answer','giving a toast nobody toasted back',1,'v1'),
('v1-a-044','answer','the friend who documents everything but posts nothing',1,'v1'),
('v1-a-045','answer','an emotional support outside voice',1,'v1'),
('v1-a-046','answer','a motivational speech delivered to a parking meter',1,'v1'),
('v1-a-047','answer','the "are you seeing this" elbow nudge',1,'v1'),
('v1-a-048','answer','somebody''s situationship proposal getting rejected',1,'v1'),
('v1-a-049','answer','fighting for your life in a bathroom mirror selfie',1,'v1'),
('v1-a-050','answer','the outfit change that changed nothing',1,'v1'),
('v1-a-051','answer','a bottle-service sparkler that outshone the birthday',1,'v1'),
('v1-a-052','answer','a heartfelt apology text sent to the wrong ex',1,'v1'),
('v1-a-053','answer','someone practicing their walk like it''s the Met Gala',1,'v1'),
('v1-a-054','answer','the group chat poll nobody voted on',1,'v1'),
('v1-a-055','answer','a pocket full of other people''s gum',1,'v1'),
('v1-a-056','answer','pretending the smoke machine was for them',1,'v1'),
('v1-a-057','answer','the "we should do this every weekend" lie',1,'v1'),
('v1-a-058','answer','an umbrella drink at a dive bar, ordered shamelessly',1,'v1'),
('v1-a-059','answer','the friend who networks mid-dance',1,'v1'),
('v1-a-060','answer','a coat-check ticket for a jacket that isn''t yours',1,'v1'),
('v1-a-061','answer','someone''s mom liking their 4 AM story',1,'v1'),
('v1-a-062','answer','a compliment so drunk it becomes poetry',1,'v1'),
('v1-a-063','answer','the promoter''s "you''re on the list" that means nothing',1,'v1'),
('v1-a-064','answer','an entire bottle of hotel shampoo as a souvenir',1,'v1'),
('v1-a-065','answer','the couple making everyone third wheel on purpose',1,'v1'),
('v1-a-066','answer','a hand stamp that will not come off before Monday',1,'v1'),
('v1-a-067','answer','someone explaining crypto to the bartender',1,'v1'),
('v1-a-068','answer','the friend who falls asleep standing up',1,'v1'),
('v1-a-069','answer','a situationship status meeting in the smoking section',1,'v1'),
('v1-a-070','answer','three layers of cologne applied like war paint',1,'v1'),
('v1-a-071','answer','the "you had to be there" story nobody asked for',1,'v1'),
('v1-a-072','answer','a guy doing pull-ups on the subway pole',1,'v1'),
('v1-a-073','answer','someone''s actual business card, laminated',1,'v1'),
('v1-a-074','answer','the 6 AM diner summit meeting',1,'v1'),
('v1-a-075','answer','a bag of ice that becomes the night''s currency',1,'v1'),
('v1-a-076','answer','someone reenacting the whole fight for the Uber driver',1,'v1'),
('v1-a-077','answer','the "I''m five minutes away" lie sent from bed',1,'v1'),
('v1-a-078','answer','a group dance so synchronized it felt rehearsed',1,'v1'),
('v1-a-079','answer','somebody crying happy tears into a quesadilla',1,'v1'),
('v1-a-080','answer','the friend who gives everyone a score for the night',1,'v1'),
('v1-a-081','answer','a first-name basis with the taco truck guy',1,'v1'),
('v1-a-082','answer','someone doing their skincare routine in the club bathroom',1,'v1'),
('v1-a-083','answer','a mystery bruise with an epic origin story',1,'v1'),
('v1-a-084','answer','the "lowkey" party that has a dress code',1,'v1'),
('v1-a-085','answer','someone''s personality changing at the third drink',1,'v1'),
('v1-a-086','answer','a phone at 2% still being used as a flashlight',1,'v1'),
('v1-a-087','answer','the friend who treats every night like a season finale',1,'v1'),
('v1-a-088','answer','an outfit so cold it required its own security',1,'v1'),
('v1-a-089','answer','a "quick check-in" that becomes a hostage situation',1,'v1'),
('v1-a-090','answer','someone''s rogue aunt tearing up the dance floor',1,'v1'),
('v1-a-091','answer','the table reservation nobody remembers making',1,'v1'),
('v1-a-092','answer','a kiss that got reviewed like a Yelp page',1,'v1'),
('v1-a-093','answer','someone ordering "whatever''s strongest" and regretting it instantly',1,'v1'),
('v1-a-094','answer','the dramatic exit followed by coming right back in',1,'v1'),
('v1-a-095','answer','a voice memo that sounds like a hostage tape',1,'v1'),
('v1-a-096','answer','someone''s birthday list demands, read aloud like a constitution',1,'v1'),
('v1-a-097','answer','the stranger who becomes your best friend for exactly one song',1,'v1'),
('v1-a-098','answer','a pair of heels carried like a clutch bag by midnight',1,'v1'),
('v1-a-099','answer','the "vibes consultant" nobody appointed',1,'v1'),
('v1-a-100','answer','an argument about the best route home that outlasts the ride',1,'v1'),
('v1-a-101','answer','someone doing squad roll call like it''s a heist',1,'v1'),
('v1-a-102','answer','the bathroom attendant who knows all the tea',1,'v1'),
('v1-a-103','answer','a full speech about loyalty delivered to strangers',1,'v1'),
('v1-a-104','answer','someone''s work badge still clipped to their going-out fit',1,'v1'),
('v1-a-105','answer','the "who''s pulling up" text sent to 40 people',1,'v1'),
('v1-a-106','answer','a grown man losing a dance battle to a child',1,'v1'),
('v1-a-107','answer','the lighting that makes everyone look guilty',1,'v1'),
('v1-a-108','answer','someone charging their phone behind the bar like rent is paid',1,'v1'),
('v1-a-109','answer','a friendship forged entirely in the smoking area',1,'v1'),
('v1-a-110','answer','the overconfident "I''ve been here before" guy who got lost',1,'v1'),
('v1-a-111','answer','a snack bought at the gas station like it''s fine dining',1,'v1'),
('v1-a-112','answer','someone doing closing-time math out loud',1,'v1'),
('v1-a-113','answer','the playlist that got hijacked by one bad request',1,'v1'),
('v1-a-114','answer','a karaoke mic that should have been confiscated',1,'v1'),
('v1-a-115','answer','the person still talking about their Europe trip from 2019',1,'v1'),
('v1-a-116','answer','a group photo where everyone blinked at once',1,'v1'),
('v1-a-117','answer','someone who treats the coat rack like a throne room',1,'v1'),
('v1-a-118','answer','the "innocent question" that started the argument',1,'v1'),
('v1-a-119','answer','a bouncer giving life advice at the door',1,'v1'),
('v1-a-120','answer','the mutual friend who enables every bad idea',1,'v1'),
('v1-a-121','answer','someone showing the bartender their step count',1,'v1'),
('v1-a-122','answer','a dramatic reveal that got zero reaction',1,'v1'),
('v1-a-123','answer','the "designated texter" who updates everyone''s moms',1,'v1'),
('v1-a-124','answer','an accidental confession made over fries',1,'v1'),
('v1-a-125','answer','someone''s situationship timeline being fact-checked live',1,'v1'),
('v1-a-126','answer','the DJ''s obligatory pause for "make some noise"',1,'v1'),
('v1-a-127','answer','a phone found in a place that raises questions',1,'v1'),
('v1-a-128','answer','someone hyping their own entrance to nobody',1,'v1'),
('v1-a-129','answer','the girl in the bathroom who now has your number',1,'v1'),
('v1-a-130','answer','a lecture on "how the club works" from someone who doesn''t',1,'v1'),
('v1-a-131','answer','the pizza order placed "for the table" eaten by one person',1,'v1'),
('v1-a-132','answer','someone''s aunt''s margarita recipe, weaponized',1,'v1'),
('v1-a-133','answer','a motivational poster energy applied to a stranger''s breakup',1,'v1'),
('v1-a-134','answer','the "we never do this" lie everyone tells',1,'v1'),
('v1-a-135','answer','an exit survey nobody asked for but everyone filled out',1,'v1'),
('v1-a-136','answer','someone rating the night before it''s over',1,'v1'),
('v1-a-137','answer','a dance move that should require a permit',1,'v1'),
('v1-a-138','answer','the person who saves seats by laying across them',1,'v1'),
('v1-a-139','answer','a mutual breakup negotiated at the bar',1,'v1'),
('v1-a-140','answer','someone''s "big announcement" that was just their parking spot',1,'v1'),
('v1-a-141','answer','the friend who orders waters then takes credit for hydrating everyone',1,'v1'),
('v1-a-142','answer','a situation so bad it gets its own highlight reel',1,'v1'),
('v1-a-143','answer','the person who knows the DJ (they do not)',1,'v1'),
('v1-a-144','answer','a coat so dramatic it needed its own RSVP',1,'v1'),
('v1-a-145','answer','the group''s shared villain origin story',1,'v1'),
('v1-a-146','answer','someone treating the smoking section like a therapy couch',1,'v1'),
('v1-a-147','answer','a toast so long the drinks got warm',1,'v1'),
('v1-a-148','answer','the person whose entire personality is "back from Miami"',1,'v1'),
('v1-a-149','answer','a deep-cut song that resurrected the whole room',1,'v1'),
('v1-a-150','answer','the friend who FaceTimes the group they''re standing in',1,'v1'),
('v1-a-151','answer','someone''s "chill kickback" that has a bouncer',1,'v1'),
('v1-a-152','answer','a pep talk given to the mirror and accepted',1,'v1'),
('v1-a-153','answer','the photo pose that took 45 minutes to nail',1,'v1'),
('v1-a-154','answer','an unnecessary lap around the venue to be seen',1,'v1'),
('v1-a-155','answer','someone holding court on a barstool like it''s a throne',1,'v1'),
('v1-a-156','answer','the "wrong Uber" that became the best part of the night',1,'v1'),
('v1-a-157','answer','a birthday entrance so extra the bouncer applauded',1,'v1'),
('v1-a-158','answer','the friend who adopts every stray at the party',1,'v1'),
('v1-a-159','answer','a full relationship conducted via bathroom-mirror notes',1,'v1'),
('v1-a-160','answer','someone''s grandma getting tagged in the afters photo',1,'v1')
on conflict (id) do nothing;
